# Generated by Django 2.1.4 on 2019-06-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_pk', models.IntegerField()),
                ('file', models.FileField(upload_to='C:\\Users\\gefen\\FinalProject\\Backend\\media')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('info', models.CharField(default='', max_length=100)),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('is_test', models.BooleanField(default=True)),
                ('content_pk', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('answer1', models.CharField(max_length=1000)),
                ('answer2', models.CharField(max_length=1000)),
                ('answer3', models.CharField(max_length=1000)),
                ('answer4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('top_three_users_pks', models.CharField(max_length=1000)),
                ('top_three_scores', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('questions', models.ManyToManyField(to='bcademy.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SmallTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('info', models.CharField(max_length=2500)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_pk', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_taken', models.DateTimeField(verbose_name='Date due')),
                ('milliseconds_learned', models.IntegerField(default=0)),
                ('small_topics', models.ManyToManyField(to='bcademy.SmallTopic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(to='bcademy.User'),
        ),
        migrations.AddField(
            model_name='smalltopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.Subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.Subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='users_that_played',
            field=models.ManyToManyField(to='bcademy.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='small_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.SmallTopic'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.Subject'),
        ),
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(to='bcademy.User'),
        ),
    ]
