# Generated by Django 2.1.4 on 2019-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='milliseconds_learned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
