# Generated by Django 2.1.4 on 2019-01-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smalltopic',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
