# Generated by Django 2.1.4 on 2019-02-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='info',
            field=models.CharField(default='a screenshot', max_length=100),
            preserve_default=False,
        ),
    ]
