# Generated by Django 2.1.4 on 2019-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0002_smalltopic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='small_topics',
            field=models.ManyToManyField(to='bcademy.SmallTopic'),
        ),
    ]
