# Generated by Django 2.1.4 on 2019-02-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0002_document_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
