# Generated by Django 2.1.4 on 2019-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0003_test_small_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='summerize',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
