# Generated by Django 2.1.4 on 2019-01-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0004_auto_20190129_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='summerize',
        ),
    ]
