# Generated by Django 2.1.4 on 2019-04-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0005_remove_user_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('top_three_users_pks', models.CharField(max_length=1000)),
                ('top_three_scores', models.CharField(max_length=1000)),
                ('questions', models.ManyToManyField(to='bcademy.Question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcademy.Subject')),
                ('users_that_played', models.ManyToManyField(to='bcademy.User')),
            ],
        ),
    ]
