# Generated by Django 2.1.4 on 2019-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_taken',
            field=models.DateField(verbose_name='Date due'),
        ),
    ]
