# Generated by Django 2.1.4 on 2019-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcademy', '0002_auto_20190103_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_taken',
            field=models.DateTimeField(verbose_name='Date due'),
        ),
    ]
